close all; clc; clear;

[mdot_comp, hOut_comp, Pdot_Comp, Qdot_cond, hOut_cond, ...
    POut_cond, tOut_air_cond, M_cond, DP_ref_cond, mdot_exp, hOut_exp, Qdot_evap, hOut_evap, ...
    POut_evap, tOut_air_evap, M_evap, DP_ref_evap, P_1, P_2, P_3, P_4, h_1, h_3] ...
    = VaporCCModelreducedto6variables(1000,	2000, 2000,	1000, 420, 230, 1)


